import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import PathCheck from "@/components/PathCheck";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PathCheck>{children}</PathCheck>
        <div className="relative bg-blue-50" style={{ zIndex: 2 }}>
          <Nav />
          {children}
        </div>
        <div className="dark:bg-neutral-900  items-center justify-center flex sticky bottom-0 z-0">
          <Footer />
        </div>
      </body>
    </html>
  );
}
